(function(d){d.element=function(b,c,d){var e="class hidden id style title role".split(" ");Array.isArray(d)&&e.concat(d);this.content=[];this.content.push("<"+b);if(Array.isArray(e)&&"object"===typeof c)for(d=0;d<e.length;d++)c.hasOwnProperty(e[d])&&this.content.push(new attribute(e[d],c[e[d]]));if(void 0!==c&&"object"===typeof c&&void 0!==c.data&&Array.isArray(c.data))for(e=0;e<c.data.length;e++)"object"===typeof c.data[e]&&this.content.push(new attribute("data-"+c.data[e].name,c.data[e].value));
void 0!==c&&"object"===typeof c&&void 0!==c.child?(this.content.push(">"),this.content.push(c.child),this.content.push("</"+b+">")):this.content.push("/>")};d.attribute=function(b,c){this.content=[];this.content.push(" "+b+'="'+c+'"')};d.events=function(){this.events=[]};d.core=function(){this.events=[];this.globals=new rifGlobals};d.template=function(b){this.core=b;this.content=""};d.template.prototype.load=function(b,c){this.create(b);return c(this.content)};d.template.prototype.create=function(b){if(Array.isArray(b))for(var c=
0;c<b.length;c++)this.create(b[c]);else if("object"===typeof b)this.create(b.content);else if("string"===typeof b||"number"===typeof b)this.content+=b};d.events.prototype.addEvent=function(b){var c=null;if(void 0!==b.id)c=document.getElementById(b.id),void 0!==b.event&&void 0!==b.callback&&(c.addEventListener(b.event,b.callback),this.events.push(b));else if(void 0!==b["class"]&&(c=document.getElementsByClassName(b["class"]),0<c.length&&Array.isArray(c)))for(var d=0;d<c.length;d++)void 0!==b.event&&
void 0!==b.callback&&(c[d].addEventListener(b.event,b.callback),this.events.push(b))};d.core.prototype.load=function(b,c,d){(new template(this.core)).load(b,function(b){if(!1===b)alert("Page not found");else{if(void 0!==c&&void 0===d&&"function"===typeof c){var f=document.getElementById("mainContainer");null!==f&&(f.innerHTML=b);return c()}if(void 0!==c&&void 0!==d&&"string"===typeof c&&"function"===typeof d)return f=document.getElementById(c),null!==f&&(f.innerHTML=b),d();f=document.getElementById("mainContainer");
null!==f&&(f.innerHTML=b)}})}})(this);
(function(d){d.a=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("a","href download media name id target role title style".split(" "),c)};d.form=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("form",c,"accept accept-charset action autocomplete enctype method name novalidate target".split(" "))};d.h1=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("h1",c)};d.h2=function(b){var c={};"string"===typeof b?
c.child=b:c=b;this.content=new element("h2",c)};d.h3=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("h3",c)};d.h4=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("h4",c)};d.h5=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("h5",c)};d.h6=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("h6",c)};d.pre=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("pre",
c)};d.hr=function(){this.content=new element("hr")};d.span=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("span",c)};d.section=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("section",c)};d.progress=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("progress",c,["max","value"])};d.iframe=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("iframe",c,"align frameborder height longdesc marginheight marginwidth name sandbox scrolling seamless src srcdoc width".split(" "))};
d.header=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("header",c)};d.footer=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("footer",c)};d.fieldset=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("fieldset",c)};d.code=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("code",c)};d.canvas=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("canvas",
c,["height","width"])};d.br=function(){this.content=new element("br")};d.strong=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("strong",c)};d.caption=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("caption",c)};d.mark=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("mark",c)};d.address=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("address",c)};d.article=function(b){var c=
{};"string"===typeof b?c.child=b:c=b;this.content=new element("article",c)};d.aside=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("aside",c)};d.tbody=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("tbody",c)};d.thead=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("thead",c)};d.tfoot=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("tfoot",c)};d.td=function(b){var c={};
"string"===typeof b?c.child=b:c=b;this.content=new element("td",c,["colspan","header_id","rowspan"])};d.th=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("td",c,"abbr colspan headers rowspan scope sorted".split(" "))};d.title=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("title",c)};d.tr=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("tr",c)};d.label=function(b){var c={};"string"===typeof b?c.child=
b:c=b;this.content=new element("label",c,["for","form"])};d.table=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("table",c,["sortable"])};d.ul=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("ul",c)};d.ol=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("ol",c,["reversed","start","type"])};d.main=function(b){var c={};"string"===typeof b&&(c.child=b);c={};"string"===typeof b?c.child=b:c=b;this.content=new element("main",
c)};d.li=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("li",c)};d.video=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("audio",c,"autoplay controls height loop muted poster preload src width".split(" "))};d.audio=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("audio",c,"autoplay controls loop muted preload src".split(" "))};d.img=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("img",
c,"align alt border height hspace src width".split(" "))};d.input=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("input",c,"accept align alt autocomplete autofocus checked disabled form formAction formenctype formmethod formnovalidate formtarget height list max maxlength min multiple name id pattern placeholder readonly required size src type value width title style".split(" "))};d.textarea=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("textarea",
c,"autofocus cols disabled form maxlength placeholder readonly required rows wrap".split(" "))};d.select=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("select",c,"autofocus disabled form multiple name required size".split(" "))};d.option=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("option",c,["value","selected","disabled","label"])};d.p=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("p",c)};d.div=
function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("div",c)};d.nav=function(b){this.content=new element("nav","class hidden id style title role".split(" "),elementParams)};d.button=function(b){var c={};"string"===typeof b?c.child=b:c=b;this.content=new element("button",c)}})(this);
(function(d){d.navBarForm=function(b){this.content=[];if(void 0!==b.fields)for(var c=0;c<b.fields.length;c++)forms.child.push(new div({"class":"form-group",child:[b.fields[c]]}))};d.pageHeader=function(b){this.content=[];this.content.push(new div({"class":void 0!==b["class"]?b["class"]:"page-header",child:void 0!==b.child?b.child:[]}))};d.badge=function(b){this.content=[];this.content.push(new span({"class":void 0!==b["class"]?b["class"]:"badge",child:void 0!==b.number?b.number:"0"}))};d.extLabel=
function(b){this.content=[];this.content.push(new span({"class":void 0!==b["class"]?b["class"]:"label label-default",child:void 0!==b.child?b.child:[]}))};d.pagination=function(b){this.content=[];this.content.push(new nav({child:[new ul({"class":void 0!==b["class"]?b["class"]:"pagination",child:void 0!==b.child?b.child:[]})]}))};d.breadcrumb=function(b){this.content=[];this.content.push(new ol({"class":"breadcrumb",child:void 0!==b.child?b.child:[]}))};d.navbar=function(b){this.content=[];var c={};
void 0!==b["class"]?c["class"]=b["class"]:void 0!==b.type&&(c["class"]="navbar navbar-"+b.type);b.id&&(c.id=b.id);c.child=[];b.header&&c.child.push(new div({"class":"navbar-header",child:[new button({type:"button","class":b.header["class"],attributes:[{"data-togle":"collapse","data-target":"#"+b.header.target}],child:[new span('<span class="sr-only">Toggle navigation</span>'),new span('<span class="icon-bar"></span>'),new span('<span class="icon-bar"></span>'),new span('<span class="icon-bar"></span>')]}),
new a({"class":"navbar-brand",href:b.header.brand.link,child:b.header.brand.child})]}));void 0!==b.collapse&&c.child.push(new div({"class":"collapse navbar-collapse",id:b.header.target,child:[new ul({"class":"nav navbar-nav",child:b.collapse.child})]}));this.content.push(c)};d.pills=function(b){this.content=[];var c={"class":"nav nav-pills"};void 0!==b["class"]&&(c["class"]+=" "+b["class"]);void 0!==b.id&&(c.id=b.id);void 0!==b.child&&(c.child=b.child);this.content.push(new ul(c))};d.nav_stacked=
function(b){this.content=[];var c={"class":"nav nav-pills nav-stacked"};void 0!==b["class"]&&(c["class"]+=" "+b["class"]);void 0!==b.id&&(c.id=b.id);void 0!==b.child&&(c.child=b.child);this.content.push(new ul(c))};d.tabs=function(b){this.content=[];var c={"class":"nav nav-tabs"};void 0!==b["class"]&&(c["class"]+=" "+b["class"]);void 0!==b.id&&(c.id=b.id);void 0!==b.child&&(c.child=b.child);this.content.push(new ul(c))};d.glyph=function(b){this.content=[];var c={};void 0!==b.icon&&(c["class"]="glyphicon glyphicon-"+
b.icon);void 0!==b.child&&(c.child=b.child);this.content.push(new span(c))};d.jumbotron=function(b){this.content=[];var c={"class":"jumbotron"};if(void 0!==b&&Array.isArray(b)){c.child=[];for(var d=0;d<b.length;d++)c.child.push(b[d])}this.content.push(new div(c))};d.alert=function(b,c,d){this.content=[];this.content.push(new div({"class":"alert alert-"+(void 0!==b?b:"danger")+(void 0!==c&&!0===c?" hidden":""),child:void 0!==d?d:""}))};d.column=function(b){this.content=[];this.content.push(new div(b))};
d.row=function(b,c){this.content=[];void 0===c&&(c={});void 0===c["class"]&&(c["class"]="row");c.child=[];if(void 0!==b&&Array.isArray(b))for(var d=0;d<b.length;d++)c.child.push(b[d]);this.content.push(new div(c))};d.container=function(b,c){this.content=[];void 0===c&&(c={});void 0===c["class"]&&(c["class"]="container");if(void 0!==b&&Array.isArray(b)){c.child=[];for(var d=0;d<b.length;d++)c.child.push(b[d])}this.content.push(new div(c))}})(this);
