(function(c){c.element=function(b,a,c){var d="class hidden id style title role".split(" ");Array.isArray(c)&&d.concat(c);this.content=[];this.content.push("<"+b);if(Array.isArray(d)&&"object"===typeof a)for(c=0;c<d.length;c++)a.hasOwnProperty(d[c])&&this.content.push(new attribute(d[c],a[d[c]]));if(void 0!==a&&"object"===typeof a&&void 0!==a.data&&Array.isArray(a.data))for(d=0;d<a.data.length;d++)"object"===typeof a.data[d]&&this.content.push(new attribute("data-"+a.data[d].name,a.data[d].value));
void 0!==a&&"object"===typeof a&&void 0!==a.child?(this.content.push(">"),this.content.push(a.child),this.content.push("</"+b+">")):this.content.push("/>")};c.attribute=function(b,a){this.content=[];this.content.push(" "+b+'="'+a+'"')};c.events=function(){this.events=[]};c.core=function(){this.events=[];this.globals=new rifGlobals};c.template=function(b){this.core=b;this.content=""};c.template.prototype.load=function(b,a){this.create(b);return a(this.content)};c.template.prototype.create=function(b){if(Array.isArray(b))for(var a=
0;a<b.length;a++)this.create(b[a]);else if("object"===typeof b)this.create(b.content);else if("string"===typeof b||"number"===typeof b)this.content+=b};c.events.prototype.addEvent=function(b){var a=null;void 0!==b.id&&(a=document.getElementById(b.id));void 0!==b.event&&void 0!==b.callback&&(a.addEventListener(b.event,b.callback),this.events.push(b))};c.core.prototype.load=function(b,a,c){(new template(this.core)).load(b,function(b){if(!1===b)alert("Page not found");else{if(void 0!==a&&void 0===c&&
"function"===typeof a){var e=document.getElementById("mainContainer");null!==e&&(e.innerHTML=b);return a()}if(void 0!==a&&void 0!==c&&"string"===typeof a&&"function"===typeof c)return e=document.getElementById(a),null!==e&&(e.innerHTML=b),c();e=document.getElementById("mainContainer");null!==e&&(e.innerHTML=b)}})}})(this);
(function(c){c.a=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("a","href download media name id target role title style".split(" "),a)};c.form=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("form",a,"accept accept-charset action autocomplete enctype method name novalidate target".split(" "))};c.h1=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("h1",a)};c.h2=function(b){var a={};"string"===typeof b?
a.child=b:a=b;this.content=new element("h2",a)};c.h3=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("h3",a)};c.h4=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("h4",a)};c.h5=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("h5",a)};c.h6=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("h6",a)};c.pre=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("pre",
a)};c.hr=function(){this.content=new element("hr")};c.span=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("span",a)};c.section=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("section",a)};c.progress=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("progress",a,["max","value"])};c.iframe=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("iframe",a,"align frameborder height longdesc marginheight marginwidth name sandbox scrolling seamless src srcdoc width".split(" "))};
c.header=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("header",a)};c.footer=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("footer",a)};c.fieldset=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("fieldset",a)};c.code=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("code",a)};c.canvas=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("canvas",
a,["height","width"])};c.br=function(){this.content=new element("br")};c.strong=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("strong",a)};c.caption=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("caption",a)};c.mark=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("mark",a)};c.address=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("address",a)};c.article=function(b){var a=
{};"string"===typeof b?a.child=b:a=b;this.content=new element("article",a)};c.aside=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("aside",a)};c.tbody=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("tbody",a)};c.thead=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("thead",a)};c.tfoot=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("tfoot",a)};c.td=function(b){var a={};
"string"===typeof b?a.child=b:a=b;this.content=new element("td",a,["colspan","header_id","rowspan"])};c.th=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("td",a,"abbr colspan headers rowspan scope sorted".split(" "))};c.title=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("title",a)};c.tr=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("tr",a)};c.label=function(b){var a={};"string"===typeof b?a.child=
b:a=b;this.content=new element("label",a,["for","form"])};c.table=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("table",a,["sortable"])};c.ul=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("ul",a)};c.ol=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("ol",a,["reversed","start","type"])};c.main=function(b){var a={};"string"===typeof b&&(a.child=b);a={};"string"===typeof b?a.child=b:a=b;this.content=new element("main",
a)};c.li=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("li",a)};c.video=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("audio",a,"autoplay controls height loop muted poster preload src width".split(" "))};c.audio=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("audio",a,"autoplay controls loop muted preload src".split(" "))};c.img=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("img",
a,"align alt border height hspace src width".split(" "))};c.input=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("input",a,"accept align alt autocomplete autofocus checked disabled form formAction formenctype formmethod formnovalidate formtarget height list max maxlength min multiple name id pattern placeholder readonly required size src type value width title style".split(" "))};c.textarea=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("textarea",
a,"autofocus cols disabled form maxlength placeholder readonly required rows wrap".split(" "))};c.select=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("select",a,"autofocus disabled form multiple name required size".split(" "))};c.option=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("option",a,["value","selected","disabled","label"])};c.p=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("p",a)};c.div=
function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("div",a)};c.nav=function(b){this.content=new element("nav","class hidden id style title role".split(" "),elementParams)};c.button=function(b){var a={};"string"===typeof b?a.child=b:a=b;this.content=new element("button",a)}})(this);
(function(c){c.alert=function(b,a,c){this.content=[];this.content.push(new div({"class":"alert alert-"+(void 0!==b?b:"danger")+(void 0!==a&&!0===a?" hidden":""),child:void 0!==c?c:""}))};c.column=function(b){this.content=[];this.content.push(new div(b))};c.row=function(b,a){this.content=[];void 0===a&&(a={});void 0===a["class"]&&(a["class"]="row");a.child=[];if(void 0!==b&&Array.isArray(b))for(var c=0;c<b.length;c++)a.child.push(b[c]);this.content.push(new div(a))};c.container=function(b,a){this.content=
[];void 0===a&&(a={});void 0===a["class"]&&(a["class"]="container");if(void 0!==b&&Array.isArray(b)){a.child=[];for(var c=0;c<b.length;c++)a.child.push(b[c])}this.content.push(new div(a))}})(this);
